# This is the base configuration for all machines
# 
# Jeffrey Jose | jeffjose | Oct 26, 2015
#
- hosts: all
  tasks:
      # Dotfiles
    - name: Copy cshrc
      copy: src=/home/jeffjose/.cshrc dest=/home/jeffjose/.cshrc
    - name: Copy aliases
      copy: src=/home/jeffjose/.aliases dest=/home/jeffjose/.aliases
    - name: Copy aliases.sensitive
      copy: src=/home/jeffjose/.aliases.sensitive dest=/home/jeffjose/.aliases.sensitive
    - name: Copy prompt
      copy: src=/home/jeffjose/.prompt dest=/home/jeffjose/.prompt
    - name: Copy precmd
      copy: src=/home/jeffjose/.precmd dest=/home/jeffjose/.precmd
    - name: Copy screenrc
      copy: src=/home/jeffjose/.screenrc dest=/home/jeffjose/.screenrc
    - name: Copy gitconfig
      copy: src=/home/jeffjose/.gitconfig dest=/home/jeffjose/.gitconfig

      # Directories
    - name: Copy screen/ files
      synchronize: src=/home/jeffjose/.screen/ dest=/home/jeffjose/.screen/ recursive=yes delete=yes
    - name: Copy xrandr config
      synchronize: src=/home/jeffjose/.screenlayout/ dest=/home/jeffjose/.screenlayout/ recursive=yes delete=yes
    - name: Copy vimrc
      copy: src=/home/jeffjose/.vimrc dest=/home/jeffjose/.vimrc
    - name: Copy vim/ files
      synchronize: src=/home/jeffjose/.vim/ dest=/home/jeffjose/.vim/ recursive=yes delete=yes

      # apt-get
    - name: Install tcsh
      apt : name=tcsh
      sudo: yes
    - name: Install utilities
      apt : name=vim,htop,python-pip,ansible,screen,git,git-gui
      sudo: yes

      # easy_install python packages
    - name: Install supervisor
      easy_install: name=supervisor
      sudo: yes
    - name: Install simplejson
      easy_install: name=simplejson
      sudo: yes
    - name: Install tornado
      easy_install: name=tornado
      sudo: yes

      # Change default shell
    - name   : Make tcsh default shell (root)
      command: chsh -s /bin/tcsh
      sudo   : yes
    - name: Make tcsh default shell (jeffjose)
      user: name=jeffjose shell=/bin/tcsh
      sudo: yes

      # Copy config files
    - name: Copy /etc/hosts
      copy: src=/etc/hosts dest=/etc/hosts
      sudo: yes
